<a href="https://colab.research.google.com/github/shubhtanna/Assignment/blob/main/MLPrac12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ML PRAC 12

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets

In [ ]:
(x_train, y_train),(x_test, y_test) = datasets.boston_housing.load_data()

print('Training Set : ',x_train.shape, y_train.shape)
print('Testing Set : ',x_test.shape, y_test.shape)

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training Set :  (404, 13) (404,)
Testing Set :  (102, 13) (102,)


In [ ]:
y_train[:5]

array([15.2, 42.3, 50. , 21.1, 17.7])

In [ ]:
x_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import plot_model

model_reg = Sequential([
    Input((13,)),
    Dense(1, activation='linear')
])

model_reg.compile(optimizer='sgd', loss='msle', metrics=['accuracy', 'msle'])
model_reg.fit(x_train, y_train, epochs=10)

Epoch 1/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 9.6833 - msle: 9.6833  
Epoch 2/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.6339 - msle: 9.6339 
Epoch 3/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.6287 - msle: 9.6287 
Epoch 4/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.6763 - msle: 9.6763 
Epoch 5/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.5069 - msle: 9.5069 
Epoch 6/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.7926 - msle: 9.7926 
Epoch 7/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.6440 - msle: 9.6440 
Epoch 8/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.6247 - msle: 9.6247 
Epoch 9/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 9.7012 - msle: 9.7012 
Epoch 10/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 

In [ ]:
model_reg.evaluate(x_test, y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 9.6913 - msle: 9.6913  


[9.806747436523438, 0.0, 9.806747436523438]

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import plot_model

model_reg_1 = Sequential()
model_reg_1.add(Dense(50, activation='relu', input_shape=(x_train.shape[1],)))
model_reg_1.add(Dense(25, activation='relu'))
model_reg_1.add(Dense(12, activation='relu'))
model_reg_1.add(Dense(1, activation='linear'))

model_reg_1.compile(optimizer='adam', loss='msle', metrics=['accuracy', 'msle'])
model_reg_1.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), batch_size=64)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.0000e+00 - loss: 9.5014 - msle: 9.5014 - val_accuracy: 0.0000e+00 - val_loss: 2.6660 - val_msle: 2.6660
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 1.6452 - msle: 1.6452 - val_accuracy: 0.0000e+00 - val_loss: 0.5560 - val_msle: 0.5560
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 0.5762 - msle: 0.5762 - val_accuracy: 0.0000e+00 - val_loss: 0.8031 - val_msle: 0.8031
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0000e+00 - loss: 0.7326 - msle: 0.7326 - val_accuracy: 0.0000e+00 - val_loss: 0.7019 - val_msle: 0.7019
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0000e+00 - loss: 0.6120 - msle: 0.6120 - val_accuracy: 0.0000e+00 - val_loss: 0.4626 - val_msle: 0.4626
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0000e+00 - loss: 0.3709 - msle: 0.3709 - val_accuracy: 0.0000e+00 - val_loss: 0.2328 - val_msle: 0.2328
Epoch 7/10
7/

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

bank_ds = pd.read_csv('/content/bank (1).csv', delimiter=';')

le = LabelEncoder()

for col in ['job', 'marital', 'default', 'education', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']:
    bank_ds[col] = le.fit_transform(bank_ds[col])
bank_ds.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   30   10        1          0        0     1787        0     0        0   
1   33    7        1          1        0     4789        1     1        0   
2   35    4        2          2        0     1350        1     0        0   
3   30    4        1          2        0     1476        1     1        2   
4   59    1        1          1        0        0        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  y  
0   19     10        79         1     -1         0         3  0  
1   11      8       220         1    339         4         0  0  
2   16      0       185         1    330         1         0  0  
3    3      6       199         4     -1         0         3  0  
4    5      8       226         1     -1         0         3  0

In [ ]:
x = bank_ds.iloc[:,:-1].values
y = bank_ds.iloc[:,-1].values

from sklearn.preprocessing import StandardScaler

x_std = StandardScaler().fit_transform(x)

x_std[0]

array([-1.05626965,  1.71680374, -0.24642938, -1.64475535, -0.1307588 ,
        0.12107186, -1.14205138, -0.42475611, -0.72364152,  0.37405206,
        1.48541444, -0.7118608 , -0.57682947, -0.4072183 , -0.32041282,
        0.44441328])

In [ ]:
model_bc = Sequential()
model_bc.add(Dense(20, activation='relu', input_shape=(16,)))
model_bc.add(Dense(5, activation='relu'))
model_bc.add(Dense(1, activation='sigmoid'))

model_bc.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_bc.fit(x, y, epochs=10, batch_size=128, validation_split=0.2)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


29/29 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.5651 - loss: 7.6971 - val_accuracy: 0.7271 - val_loss: 2.3865
Epoch 2/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7337 - loss: 2.1668 - val_accuracy: 0.8309 - val_loss: 1.0095
Epoch 3/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8290 - loss: 1.2538 - val_accuracy: 0.8387 - val_loss: 0.9098
Epoch 4/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8500 - loss: 0.9409 - val_accuracy: 0.8663 - val_loss: 0.8072
Epoch 5/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8431 - loss: 0.7821 - val_accuracy: 0.8619 - val_loss: 0.7624
Epoch 6/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8389 - loss: 0.8459 - val_accuracy: 0.8674 - val_loss: 0.7418
Epoch 7/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8570 - loss: 0.8940 - val_accuracy: 0.8365 - val_loss: 0.7677
Epoch 8/10
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8528 - loss: 0.7423 - val_accuracy: 0.8508 - val_loss: 0.6893
Epo

In [ ]:
pred_proba = model_bc.predict(x)

pred = []

for proba in pred_proba:
    if proba>=0.5:
        pred.append(1)
    else:
        pred.append(0)

142/142 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [ ]:
from sklearn.metrics import classification_report

cls = classification_report(y, pred)
print(cls)

              precision    recall  f1-score   support

           0       0.91      0.94      0.92      4000
           1       0.37      0.27      0.31       521

    accuracy                           0.86      4521
   macro avg       0.64      0.60      0.62      4521
weighted avg       0.85      0.86      0.85      4521



In [ ]:
from tensorflow.keras import losses
from tensorflow.keras import optimizers

In [ ]:
from sklearn import datasets
from tensorflow.keras.utils import to_categorical

iris_ds = datasets.load_iris()

x = iris_ds.data
y = iris_ds.target

y_cat = to_categorical(y, num_classes=3)

model_mc = Sequential()
model_mc.add(Dense(10, activation='relu', input_shape=(4,)))
model_mc.add(Dense(5, activation='relu'))
model_mc.add(Dense(3, activation='softmax'))

model_mc.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_mc.fit(x, y_cat, epochs=4, batch_size=64, validation_split=0.2)

Epoch 1/4


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 211ms/step - accuracy: 0.4184 - loss: 1.3716 - val_accuracy: 0.0000e+00 - val_loss: 4.5671
Epoch 2/4
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4236 - loss: 1.3777 - val_accuracy: 0.0000e+00 - val_loss: 4.4455
Epoch 3/4
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4236 - loss: 1.3363 - val_accuracy: 0.0000e+00 - val_loss: 4.3271
Epoch 4/4
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4340 - loss: 1.2792 - val_accuracy: 0.0000e+00 - val_loss: 4.2126


In [ ]:
import numpy as np
x.shape

np.unique(y)

array([0, 1, 2])

In [ ]:
y_pred_proba = model_mc.predict(x)

y_pred = []
for proba in y_pred_proba:
    y_pred.append(np.argmax(proba))

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step


In [ ]:
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.33      1.00      0.50        50
           1       0.00      0.00      0.00        50
           2       0.00      0.00      0.00        50

    accuracy                           0.33       150
   macro avg       0.11      0.33      0.17       150
weighted avg       0.11      0.33      0.17       150



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
